Poggers Report 31
space-wizards/website-content pull request #27
Opened 2022-03-16 19:20 UTC by ike709

TODO:

- [ ] Patrons list
- [ ] Bully people for feedback
- [ ] Address feedback

2022-03-16 19:24 UTC, moonheart08 commented on content/post/22-03-16-progress-report-31.md
> +Space Station 14 now has a [wiki](https://wiki.spacestation14.io/wiki/Main_Page)! It's a one-stop shop for everything you need to know in order to get that greentext.
Perhaps mention that it is open to contributions? People can log in with their SS14 account.

2022-03-16 19:29 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +Space Station 14 now has a [wiki](https://wiki.spacestation14.io/wiki/Main_Page)! It's a one-stop shop for everything you need to know in order to get that greentext.
```suggestion
Space Station 14 now has a [wiki](https://wiki.spacestation14.io/wiki/Main_Page)! It's a one-stop shop for everything you need to know in order to get that greentext, and anyone with a Space Station 14 account is able to contribute.
```

2022-03-16 19:37 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*Contributed by Daemon*
```suggestion
*Contributed by Daemon and Mithrandalf*
```

2022-03-16 19:41 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, Jack Fox, Julian Giebel, JustinTime, Júl
```suggestion
*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Daemon, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, Jack Fox, Julian Giebel, JustinTime, Júlio César Ueti, Kara D, Lamrr, Leon Friedrich, LittleBuilderJane, Matz05, Michael Phillips, Moony, Morbo, Neith, Pancake, Paul, Peptide90, Pieter-Jan Briers, Plasmaguy, Rane, Sam Weaver, ScalyChimp, ShadowCommander, T-Stalker, TaralGit, Vera Aguilera Puerto, Willhelm53, WlarusFromDaSpace, Ygg01, Zymem, bloodrizer, keronshb, metalgearsloth, mirrorcult, pointer-to-null, router, sewerpig, wrexbe*
```

2022-03-16 19:41 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*354 commits, authored by: metalgearsloth, Leon Friedrich, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJ
```suggestion
*354 commits, authored by: metalgearsloth, Leon Friedrich, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgrashin, Michael Phillips, Morbo, Sam Weaver, Paul Ritter, Daemon, Delete69, ElectroJr, Jack Fox, Júlio César Ueti, Paul, ScalyChimp, moonheart08, BubblegumBlue, Charlese2, DrSmugleaf, E F R, Fishfish458, T-Stalker, Zymem, Aaron Mell, Acruid, Clyybber, Demetre Beroshvili, Flipp Syder, Javier Guardia Fernández, Julian Giebel, JustinTime, Matz05, Neith, Plasmaguy, TaralGit, Willhelm53, WlarusFromDaSpace, Ygg01, bloodrizer, keronshb, pointer-to-null, router, sewerpig*
```

2022-03-16 19:42 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*354 commits, authored by: metalgearsloth, Leon Friedrich, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJ
```suggestion
*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgrashin, Michael Phillips, Morbo, Sam Weaver, Paul Ritter, ZeroDayDaemon, Delete69, ElectroJr, Jack Fox, Júlio César Ueti, Paul, ScalyChimp, moonheart08, BubblegumBlue, Charlese2, DrSmugleaf, E F R, Fishfish458, T-Stalker, Zymem, Aaron Mell, Acruid, Clyybber, Demetre Beroshvili, Flipp Syder, Javier Guardia Fernández, Julian Giebel, JustinTime, Matz05, Neith, Plasmaguy, TaralGit, Willhelm53, WlarusFromDaSpace, Ygg01, bloodrizer, keronshb, pointer-to-null, router, sewerpig*
```

2022-03-16 19:42 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*354 commits, authored by: metalgearsloth, Leon Friedrich, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJ
```suggestion
*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgrashin, Michael Phillips, Morbo, Sam Weaver, Paul Ritter, Daemon, Delete69, ElectroJr, Jack Fox, Júlio César Ueti, Paul, ScalyChimp, moonheart08, BubblegumBlue, Charlese2, DrSmugleaf, E F R, Fishfish458, T-Stalker, Zymem, Aaron Mell, Acruid, Clyybber, Demetre Beroshvili, Flipp Syder, Javier Guardia Fernández, Julian Giebel, JustinTime, Matz05, Neith, Plasmaguy, TaralGit, Willhelm53, WlarusFromDaSpace, Ygg01, bloodrizer, keronshb, pointer-to-null, router, sewerpig*
```

2022-03-16 21:30 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgras
```suggestion
*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgrashin, Michael Phillips, Morbo, Sam Weaver, Paul Ritter, Daemon, Delete69, ElectroJr, DubiousDoggo, Júlio César Ueti, Paul, ScalyChimp, moonheart08, BubblegumBlue, Charlese2, DrSmugleaf, E F R, Fishfish458, T-Stalker, Zymem, Aaron Mell, Acruid, Clyybber, Demetre Beroshvili, Flipp Syder, Javier Guardia Fernández, Julian Giebel, JustinTime, Matz05, Neith, Plasmaguy, TaralGit, Willhelm53, WlarusFromDaSpace, Ygg01, bloodrizer, keronshb, pointer-to-null, router, sewerpig*
```

2022-03-16 21:30 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Daemon, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, Jack Fox, Julian Giebel, JustinT
```suggestion
*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Daemon, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, DubiousDoggo, Julian Giebel, JustinTime, Júlio César Ueti, Kara D, Lamrr, LittleBuilderJane, Matz05, Michael Phillips, Moony, Morbo, Neith, Pancake, Paul, Peptide90, Pieter-Jan Briers, Plasmaguy, Rane, Sam Weaver, ScalyChimp, ShadowCommander, T-Stalker, TaralGit, Vera Aguilera Puerto, Willhelm53, WlarusFromDaSpace, Ygg01, Zymem, bloodrizer, keronshb, metalgearsloth, mirrorcult, pointer-to-null, router, sewerpig, wrexbe*
```

2022-03-17 19:38 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +`Content.MapRenderer` has been added as a new project that can turn a map file and render it as an image. It's extremely useful for development, updating the wiki, and more.
```suggestion
`Content.MapRenderer` has been added as a new project that can take a map file and render it as an image. It's extremely useful for development, updating the wiki, and more.
```

2022-03-17 19:38 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +`Content.MapRenderer` has been added as a new project that can turn a map file and render it as an image. It's extremely useful for development, updating the wiki, and more.
```suggestion
`Content.MapRenderer` has been added as a new project that can take a map file and render it as an image. It's extremely useful for development, updating the wiki, and more.
```

2022-03-17 20:43 UTC, ike709 commented on content/post/22-03-16-progress-report-31.md
> +*Contributed by DrSmugleaf and mirrorcult*
```suggestion
*Contributed by DrSmugleaf, moony, and mirrorcult*
```

2022-03-18 17:19 UTC, DrSmugleaf requested changes

2022-03-18 17:19 UTC, DrSmugleaf commented on content/post/22-03-16-progress-report-31.md
> +*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgras
Duplicate names.

```suggestion
*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgrashin, Michael Phillips, Morbo, Sam Weaver, Daemon, Delete69, ElectroJr, DubiousDoggo, Júlio César Ueti, Paul, ScalyChimp, BubblegumBlue, Charlese2, DrSmugleaf, E F R, Fishfish458, T-Stalker, Zymem, Aaron Mell, Acruid, Clyybber, Demetre Beroshvili, Flipp Syder, Julian Giebel, JustinTime, Matz05, Neith, Plasmaguy, TaralGit, Willhelm53, WlarusFromDaSpace, Ygg01, bloodrizer, keronshb, pointer-to-null, router, sewerpig*
```

2022-03-18 17:21 UTC, DrSmugleaf requested changes

2022-03-18 17:21 UTC, DrSmugleaf commented on content/post/22-03-16-progress-report-31.md
> +*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Daemon, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, DubiousDoggo, Julian Giebel, Jus
List of Patrons is wrong, I'm not one of them and Tomeno is missing for example.

2022-03-18 17:28 UTC, DrSmugleaf requested changes

2022-03-18 17:28 UTC, DrSmugleaf commented on content/post/22-03-16-progress-report-31.md
> +*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Daemon, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, DubiousDoggo, Julian Giebel, Jus
Correct list:

```suggestion
*Phillip Inman, Zakanater 19, Jex N, Peter "Azmond" Newhouse, Seija, Tom Cruize, Corpus Inc., Hamcha, Oxyclean114, JustanAnus, NorthwoodTodd, Collin R Terrell, Cormos Lemming, grhmhome, Spiffyfishface, Callum Tubrett, Hydration, John Edward Hamilton Barchard, Wrexbe, Frege Beach, Austin Nelson, AquaDraco, Miniwoffer, hh, Nicholas Hillblom, Florian, Viridian, Daskata, Blaise M., Jack Rose, The Hateful Flesh, Will M., spinnermaster, Koyki, Valinov, Dan Griskardian, Robin Rottstock, Altana, Durp, Joshington Awesomahee, Eric VW, Evan Armstrong, Mono, Ethan Keller, DramaBuns, KrystalDisc, Darren Brady, Zandario, Anthony Fleck, vifs_vestige, Bobberunio, CPM311, ThatGuyGW, Farewell Fire, Daniel Thompson, Tomeno*
```

2022-03-18 17:29 UTC, DrSmugleaf commented on content/post/22-03-16-progress-report-31.md
> +*Aaron Mell, Acruid, Alex Evgrashin, BubblegumBlue, Charlese2, Clyybber, Daemon, Delete69, Demetre Beroshvili, DrSmugleaf, E F R, ElectroJr, Fishfish458, Flipp Syder, DubiousDoggo, Julian Giebel, Jus
Done in [`d33a7e6` (#27)](https://github.com/space-wizards/website-content/pull/27/commits/d33a7e6311c71bc1065c548a98b3b044ea77e021)

2022-03-18 18:18 UTC, DrSmugleaf approved these changes

2022-03-18 18:22 UTC, mirrorcult requested changes

2022-03-18 18:22 UTC, mirrorcult commented on content/post/22-03-16-progress-report-31.md
> +*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, Kara D, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgras
```suggestion
*354 commits, authored by: metalgearsloth, Peptide90, Rane, Pancake, ShadowCommander, Moony, Lamrr, mirrorcult, wrexbe, Pieter-Jan Briers, Vera Aguilera Puerto, LittleBuilderJane, Alex Evgrashin, Michael Phillips, Morbo, Sam Weaver, Daemon, Delete69, ElectroJr, DubiousDoggo, Júlio César Ueti, Paul, ScalyChimp, BubblegumBlue, Charlese2, DrSmugleaf, E F R, Fishfish458, T-Stalker, Zymem, Aaron Mell, Acruid, Clyybber, Demetre Beroshvili, Flipp Syder, Julian Giebel, JustinTime, Matz05, Neith, Plasmaguy, TaralGit, Willhelm53, WlarusFromDaSpace, Ygg01, bloodrizer, keronshb, pointer-to-null, router, sewerpig*
```

2022-03-18 18:34 UTC, moonheart08 approved these changes

2022-03-18 18:34 UTC, mirrorcult approved these changes

2022-03-18 18:36 UTC, merged